version: '3.8'

services:
  nuxt-app:
    build: .
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: development
      VITE_API_BASE: https://servicodados.ibge.gov.br/api/v3/agregados
    container_name: nuxt_server